"""Vision analysis - sends images to vision-capable models for interpretation.

Supports figure interpretation, quality assessment, and multi-figure comparison
for scientific plots generated by sandbox executions.
"""

from __future__ import annotations

import base64
import json
import logging
from pathlib import Path
from typing import Any

from ulid import ULID

from .inference import InferenceClient

log = logging.getLogger("daemon.vision")

MAX_IMAGE_SIZE_BYTES = 10 * 1024 * 1024  # 10 MB

MIME_TYPES = {
    ".png": "image/png",
    ".jpg": "image/jpeg",
    ".jpeg": "image/jpeg",
    ".gif": "image/gif",
    ".webp": "image/webp",
}

DEFAULT_PROMPTS: dict[str, str] = {
    "interpret": (
        "Describe this scientific figure. What does it show? "
        "What are the key findings? Note any trends, outliers, or anomalies."
    ),
    "quality": (
        "Assess the quality of this figure for scientific publication. "
        "Comment on: clarity, labels, color choices, statistical presentation."
    ),
    "compare": (
        "Compare these two scientific figures. What changed between them? "
        "Which shows better results? Identify specific differences in "
        "trends, values, and patterns."
    ),
}

FINDINGS_SYSTEM_PROMPT = """You are a scientific figure analyst. After describing the figure,
output a JSON array of structured findings. Each finding has:
- "finding": a one-sentence description
- "confidence": "high", "medium", or "low"
- "type": one of "trend", "outlier", "pattern", "comparison", "anomaly", "observation"

Output ONLY the JSON array, no other text. Example:
[{"finding": "Temperature increases linearly from 2000-2020", "confidence": "high", "type": "trend"}]"""


class VisionAnalyzer:
    """Sends images to vision-capable models for scientific interpretation."""

    def __init__(self, inference: InferenceClient, db: Any, config: Any) -> None:
        self._inference = inference
        self._db = db
        self._config = config
        self._vision_model: str = getattr(config, "vision_model", "gpt-4o")

    def analyze_figure(
        self,
        image_path: str | Path,
        prompt: str | None = None,
        analysis_type: str = "interpret",
        linked_execution_id: str | None = None,
    ) -> dict[str, Any]:
        """Analyze a single scientific figure.

        Args:
            image_path: Path to the image file.
            prompt: Custom prompt; defaults based on analysis_type.
            analysis_type: One of "interpret", "quality", "compare".
            linked_execution_id: Optional sandbox execution that produced this figure.

        Returns:
            Dict with analysis_id, interpretation, and findings list.
        """
        path = Path(image_path)
        b64_data = self._encode_image(path)
        mime = MIME_TYPES.get(path.suffix.lower(), "image/png")

        effective_prompt = prompt or DEFAULT_PROMPTS.get(analysis_type, DEFAULT_PROMPTS["interpret"])

        # Step 1: get natural-language interpretation
        interpretation = self._call_vision(
            prompt=effective_prompt,
            images=[(b64_data, mime)],
        )

        # Step 2: extract structured findings
        findings = self._extract_findings(interpretation)

        analysis_id = str(ULID())
        self._db.insert_visual_analysis({
            "id": analysis_id,
            "image_path": str(path),
            "analysis_type": analysis_type,
            "prompt": effective_prompt,
            "interpretation": interpretation,
            "findings": findings,
            "model_used": self._vision_model,
            "linked_execution_id": linked_execution_id,
        })

        log.info(
            "Analyzed figure %s (%s): %d findings",
            path.name, analysis_type, len(findings),
        )

        return {
            "analysis_id": analysis_id,
            "interpretation": interpretation,
            "findings": findings,
        }

    def compare_figures(
        self,
        image_path_1: str | Path,
        image_path_2: str | Path,
        prompt: str | None = None,
        linked_execution_id: str | None = None,
    ) -> dict[str, Any]:
        """Compare two scientific figures side by side.

        Returns:
            Dict with analysis_id, interpretation, findings, and comparison summary.
        """
        path_1 = Path(image_path_1)
        path_2 = Path(image_path_2)

        b64_1 = self._encode_image(path_1)
        b64_2 = self._encode_image(path_2)
        mime_1 = MIME_TYPES.get(path_1.suffix.lower(), "image/png")
        mime_2 = MIME_TYPES.get(path_2.suffix.lower(), "image/png")

        effective_prompt = prompt or DEFAULT_PROMPTS["compare"]

        interpretation = self._call_vision(
            prompt=effective_prompt,
            images=[(b64_1, mime_1), (b64_2, mime_2)],
        )

        findings = self._extract_findings(interpretation)

        # Build a comparison summary from findings
        comparison = {
            "image_1": str(path_1),
            "image_2": str(path_2),
            "differences": [
                f["finding"] for f in findings if f.get("type") == "comparison"
            ],
            "summary": interpretation[:500],
        }

        analysis_id = str(ULID())
        self._db.insert_visual_analysis({
            "id": analysis_id,
            "image_path": f"{path_1}|{path_2}",
            "analysis_type": "compare",
            "prompt": effective_prompt,
            "interpretation": interpretation,
            "findings": findings,
            "model_used": self._vision_model,
            "linked_execution_id": linked_execution_id,
        })

        log.info(
            "Compared figures %s vs %s: %d findings",
            path_1.name, path_2.name, len(findings),
        )

        return {
            "analysis_id": analysis_id,
            "interpretation": interpretation,
            "findings": findings,
            "comparison": comparison,
        }

    # -- Internal helpers --------------------------------------------------

    def _encode_image(self, path: Path) -> str:
        """Read an image file and return its base64-encoded content.

        Raises FileNotFoundError if the file does not exist.
        Raises ValueError if the file is too large or has an unsupported extension.
        """
        if not path.exists():
            raise FileNotFoundError(f"Image not found: {path}")

        size = path.stat().st_size
        if size > MAX_IMAGE_SIZE_BYTES:
            raise ValueError(
                f"Image too large ({size / 1024 / 1024:.1f} MB). "
                f"Maximum is {MAX_IMAGE_SIZE_BYTES / 1024 / 1024:.0f} MB."
            )

        suffix = path.suffix.lower()
        if suffix not in MIME_TYPES:
            raise ValueError(
                f"Unsupported image format: {suffix}. "
                f"Supported: {', '.join(MIME_TYPES.keys())}"
            )

        raw = path.read_bytes()
        return base64.b64encode(raw).decode("ascii")

    def _call_vision(
        self,
        prompt: str,
        images: list[tuple[str, str]],
    ) -> str:
        """Send a vision request with one or more images.

        Args:
            prompt: Text prompt describing what to analyze.
            images: List of (base64_data, mime_type) tuples.

        Returns:
            The model's text response.
        """
        content: list[dict[str, Any]] = [
            {"type": "text", "text": prompt},
        ]
        for b64_data, mime in images:
            content.append({
                "type": "image_url",
                "image_url": {"url": f"data:{mime};base64,{b64_data}"},
            })

        messages = [{"role": "user", "content": content}]

        response = self._inference.chat(
            messages=messages,
            model=self._vision_model,
            temperature=0.3,
            max_tokens=2000,
        )
        return response.content

    def _extract_findings(self, interpretation: str) -> list[dict[str, Any]]:
        """Parse model response into structured findings via a second call.

        If structured extraction fails, returns a single finding with the full text.
        """
        messages = [
            {"role": "system", "content": FINDINGS_SYSTEM_PROMPT},
            {"role": "user", "content": interpretation},
        ]

        try:
            response = self._inference.chat(
                messages=messages,
                model=self._vision_model,
                temperature=0.1,
                max_tokens=1000,
            )
            return self._parse_findings(response.content)
        except Exception:
            log.warning("Findings extraction failed, using fallback", exc_info=True)
            return self._parse_findings(interpretation)

    def _parse_findings(self, text: str) -> list[dict[str, Any]]:
        """Parse text into a list of structured finding dicts.

        Tries JSON parsing first; falls back to a single finding with the full text.
        """
        # Try to find a JSON array in the text
        stripped = text.strip()

        # Handle markdown code fences
        if stripped.startswith("```"):
            lines = stripped.split("\n")
            # Remove first and last fence lines
            inner = "\n".join(
                line for line in lines
                if not line.strip().startswith("```")
            )
            stripped = inner.strip()

        try:
            parsed = json.loads(stripped)
            if isinstance(parsed, list):
                findings = []
                for item in parsed:
                    if isinstance(item, dict) and "finding" in item:
                        findings.append({
                            "finding": str(item["finding"]),
                            "confidence": item.get("confidence", "medium"),
                            "type": item.get("type", "observation"),
                        })
                if findings:
                    return findings
        except (json.JSONDecodeError, TypeError):
            pass

        # Fallback: single finding with full text
        return [{
            "finding": text[:500],
            "confidence": "medium",
            "type": "observation",
        }]
